version: 2
jobs:

  # Backend (Java, Gradle)
  build_backend:
    working_directory: ~/app
    docker:
      - image: gradle:4.10.2-jdk8
    steps:
      - checkout
      - restore_cache:
          key: sparkles-master-{{ checksum "settings.gradle" }}
      - run: ./gradlew test
      - save_cache:
          key: sparkles-master-{{ checksum "settings.gradle" }}
          paths:
          - ~/app/.gradle

  # Frontend (Angular)
  build_frontend:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: sparkles-master-{{ checksum  "yarn.lock" }}
      - run: yarn build
      - save_cache:
          key: sparkles-master-{{ checksum "yarn.gradle" }}
          paths:
          - ~/app/node_modules

#  build_frontend:
#    working_directory: ~/app
#    docker:
#    - image: sparkles/testcontainer:latest

workflows:
  version: 2
  build:
    jobs:
    - build_backend
    - build_frontend
