version: 2
jobs:

  # Backend (Java, Gradle)
  build_backend:
    working_directory: ~/workspace
    docker:
      - image: gradle:4.10.3-jdk8
    steps:
      - checkout
      - restore_cache:
          key: sparkles-gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
      - run:
         command: ./gradlew dependencies
         name: Pull Dependencies for Build Caching
      - save_cache:
          key: sparkles-gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
          paths:
          - ~/.gradle/caches
          - ~/workspace/.gradle
      - run:
          # command: ./gradlew test || ./gradlew test --info --scan
          command: ./gradlew test --build-cache -Dorg.gradle.caching.debug=true --scan
          name: Tests


  # Frontend (Angular)
  build_frontend:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: sparkles-latest-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: sparkles-latest-{{ checksum "yarn.lock" }}
          paths:
          - ~/workspace/node_modules
      - run:
          command: ./scripts/ci/frontend.build.sh
          name: Build
      - run:
          command: ./scripts/ci/frontend.test.sh
          name: Test
      - run:
          command: ./scripts/ci/frontend.lint.sh
          name: Lint
      - store_artifacts:
          path: ~/workspace/dist
      - store_artifacts:
          path: ~/workspace/packages/components/dist
      - store_artifacts:
          path: ~/workspace/packages/styles/dist
      - store_test_results:
          path: ~/workspace/coverage

  # Project Linting
  lint:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/workspace
    steps:
      - checkout
      - restore_cache:
          key: sparkles-latest-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: sparkles-latest-{{ checksum "yarn.lock" }}
          paths:
          - ~/workspace/node_modules
      - run:
          command: ./scripts/ci/commitlint.sh
          name: Lint Commit Messages

workflows:
  version: 2
  build:
    jobs:
    - build_backend
    - build_frontend
    - lint
