version: 2
jobs:

  # Backend (Java, Gradle)
  build_backend:
    working_directory: ~/app
    docker:
      - image: gradle:4.10.2-jdk8
    steps:
      - checkout
      - restore_cache:
          key: sparkles-master-{{ checksum "settings.gradle" }}
      - run: ./gradlew test || ./gradlew test --info --scan
      - save_cache:
          key: sparkles-master-{{ checksum "settings.gradle" }}
          paths:
          - ~/app/.gradle

  # Frontend (Angular)
  build_frontend:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: sparkles-master-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn build
      - run: xvfb-run -a yarn test
      - save_cache:
          key: sparkles-master-{{ checksum "yarn.lock" }}
          paths:
          - ~/app/node_modules

workflows:
  version: 2
  build:
    jobs:
    - build_backend
    - build_frontend
