version: 2
jobs:

  # Backend (Java, Gradle)
  build_backend:
    working_directory: ~/app
    docker:
      - image: gradle:4.10.3-jdk8
    steps:
      - checkout
      - restore_cache:
          key: sparkles-{{ .Branch }}	-{{ checksum "settings.gradle" }}
      - run: ./gradlew test || ./gradlew test --info --scan
      - save_cache:
          key: sparkles-{{ .Branch }}	-{{ checksum "settings.gradle" }}
          paths:
          - ~/app/.gradle
          - ~/app/replication/build
          - ~/app/stuff/build
          - ~/app/support/common/build
          - ~/app/support/flyway/build
          - ~/app/support/javalin/common/build
          - ~/app/support/javalin/flyway/build
          - ~/app/support/javalin/jwt/build
          - ~/app/support/javalin/keycloak-security/build
          - ~/app/support/javalin/spring-data/build
          - ~/app/support/javalin/testing/build
          - ~/app/support/jpa/build
          - ~/app/support/json/json-resources/build
          - ~/app/support/json/schema/build
          - ~/app/support/keycloak/build
          - ~/app/support/ok/moshi/build
          - ~/app/support/ok/okhttp/build
          - ~/app/support/relation/build
          - ~/app/support/replication/build
          - ~/app/support/testing/build

  # Frontend (Angular)
  build_frontend:
    docker:
    - image: angular/ngcontainer:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: sparkles-{{ .Branch }}	-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: sparkles-{{ .Branch }}	-{{ checksum "yarn.lock" }}
          paths:
          - ~/app/node_modules
      - run: ./scripts/ci.frontend.sh
      - store_artifacts:
          path: ~/app/dist
      - store_artifacts:
          path: ~/app/packages/components/dist
      - store_artifacts:
          path: ~/app/packages/styles/dist

workflows:
  version: 2
  build:
    jobs:
    - build_backend
    - build_frontend
