version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:8-jdk-browsers@sha256:a4806d6c970a2ad37fcc1ec94f79d6d5841163860877ea6ad6e697829d90cbcd

    steps:
      - checkout
      - restore_cache:
          key: sparkles-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}-{{ checksum  "yarn.lock" }}
      - run: ./gradlew test
      - save_cache:
          paths:
            - ~/app/node_modules
          key: sparkles-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}-{{ checksum  "yarn.lock" }}
