version: '3'
services:
  proxy:
    image: nginx
    container_name: proxy
    environment:
      DEFAULT_HOST: ${PROXY_HOST:-sparkles.docker}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs_vol:/etc/nginx/certs
      - proxy_vol:/etc/nginx/conf.d

  certs:
    image: busybox
    container_name: certs
    volumes:
      - certs_vol:/etc/nginx/certs

  proxy-gen:
    image: sparkles/proxy-gen
    container_name: proxy-gen
    command: -notify-sighup proxy -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - certs_vol:/etc/nginx/certs
      - proxy_vol:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: sparkles

volumes:
  proxy_vol:
  certs_vol:
